### ISSUE TITLE
Missing :latest tag in docker-hub

### ISSUE THREAD

**Issue by DeividasZilinskas** [EugenMayer/docker-image-unison#1]
running: `docker pull eugenmayer/unison` 
returns:
```
Unable to find image 'eugenmayer/unison:latest' locally
docker: Error response from daemon: manifest for eugenmayer/unison:latest not found.
```
This prevents me from starting docker-sync with unison strategy, because :latest tag is used by default.

**Comment by DeividasZilinskas** [comment]
updating docker-sync to 0.5.5 helped.

**Comment by baohx2000** [comment]
Getting this with the latest docker-sync :(

**Comment by EugenMayer** [comment]
@baohx2000 https://github.com/EugenMayer/docker-sync/issues/566
