### ISSUE TITLE
plan a new release

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-image-unison#15]
We have a couple of changes:

 - #14 
 - #12 
 - #10 

Which we might want to incorporate into a new release. I'am not sure we should opt-in in changing the default of docker-sync just right now, but at least publish a new version people can use and report back optionally. Thoughts?

**Comment by ostrolucky** [comment]
Yes please 👍

**Comment by EugenMayer** [comment]
we have a new release :)

https://hub.docker.com/layers/eugenmayer/unison/2.51.3-4.12.0/images/sha256-3fdd3ddc8a893ca4dbd46c4c4ed69e07524eedc5db61e7c38e81dab82e3ecf6b?context=repo

and

https://hub.docker.com/layers/eugenmayer/unison/2.51.4_rc2-4.12.0/images/sha256-df802956ad280e7dd6352e095e7b168fa185ffc726bcff798259a0a1649e767d?context=repo
