### ISSUE TITLE
OCaml 4.11.0 support

### ISSUE THREAD

**Issue by epchris** [EugenMayer/docker-image-unison#16]
In trying to build this docker image with OCaml 4.11.0 (to match version used in Archlinux) I had to apply this patch to the Dockerfile:

```
diff --git a/Dockerfile b/Dockerfile
index 7b67579..a9c3877 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -7,7 +7,7 @@ RUN apk update \
        && wget http://caml.inria.fr/pub/distrib/ocaml-${OCAML_VERSION:0:4}/ocaml-${OCAML_VERSION}.tar.gz \
        && tar xvf ocaml-${OCAML_VERSION}.tar.gz -C /tmp \
        && cd /tmp/ocaml-${OCAML_VERSION} \
-    && ./configure \
+    && ./configure --disable-force-safe-string \
     && make world \
     && make opt \
     && umask 022 \
```

**Comment by EugenMayer** [comment]
we are now supporting 4.12 - with an patch for unison 5.51.3 https://github.com/EugenMayer/docker-image-unison/blob/master/Dockerfile#L30 and to be honest it becomes painfull to support the matrix of OAML vs Unison compile matrix blowing up each release.

I feel you, i'am on manjaro myself. But i really do not understand why you are using unison under linux at all in the first place - use a bind mount. Thus i will not going to make the support happen on my side - sorry.
