### ISSUE TITLE
ARM version

### ISSUE THREAD

**Issue by 7a6163** [EugenMayer/docker-image-unison#17]
I used the image for Apple m1. It works well.
What do you think about building the image with ARM64? 
I think that getting more performance.

**Comment by cdaguerre** [comment]
I've spent some time trying to build this image for `arm64` but couldn't make it work. 
I created an ubuntu dockerfile here: https://github.com/cdaguerre/docker-image-unison/commit/08319b6e7f400f80d51a312de527f6cd02230af2 and use it as a custom image. Works great ;)

**Comment by EugenMayer** [comment]
Not going to work on this for now, waiting for better ARM support pushed due to M1 and jump the wagon as late as possible

**Comment by EugenMayer** [comment]
Anybody who want's to continue working on it, started it with https://github.com/EugenMayer/docker-image-unison/pull/22

**Comment by EugenMayer** [comment]
Actually it builds under ARM just fine, will merge it
