### ISSUE TITLE
Version mismatch between container (2.51.2.2) and latest Homebrew version (2.51.3.70)

### ISSUE THREAD

**Issue by ls-sam-leatherdale** [EugenMayer/docker-image-unison#18]
The latest version of the container image is 2.51.2.2
Could we get an updated version for the latest `unison` version available on Homebrew, which is 2.51.3.70?

Thanks

**Comment by EugenMayer** [comment]
What does homebrew currently offer, since we are currently buildin https://github.com/EugenMayer/docker-image-unison/pull/20/files `2.51.4_rc2` and not `2.51.3.70` - did the homebrew version move on already?looking at https://formulae.brew.sh/formula/unison it seems to be 2.51.3

**Comment by ls-sam-leatherdale** [comment]
I was under the impression that to use the `unison` sync strategy that we needed it installed on the macOS host as well as inside the container.
We ran into an issue where there was a mismatch between the container and host versions, as the Homebrew version had been upgraded.
Since then, our org has switched to using the `native` strategy, but there might still be other people using `unison` that have this problem. It's quite annoying to get Homebrew to install an older version for you.

**Comment by EugenMayer** [comment]
we will fix this issue this weekend, thus offering 2.53 variant for homebrew

**Comment by EugenMayer** [comment]
fixed via #21 which also adds the 2.51.4_rc2 build in addition
