### ISSUE TITLE
Push a combined amd64+arm64 Docker tag

### ISSUE THREAD

**Issue by hufman** [EugenMayer/docker-image-unison#27]
Thank you for this incredible Unison Docker image, which is the most popular Unison image on Dockerhub by a staggering amount!
Docker recently gained the ability to [build a combined image manifest](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/) to include multiple platforms within the same image tag. Can this be provided with the Unison image? I believe the following commands should do the trick:
```
docker manifest create eugenmayer/unison:2.51.3-4.12.0 eugenmayer/unison:2.51.3-4.12.0-AMD64 eugenmayer/unison:2.51.3-4.12.0-ARM64
docker manifest create eugenmayer/unison:latest eugenmayer/unison:2.51.3-4.12.0-AMD64 eugenmayer/unison:2.51.3-4.12.0-ARM64
docker manifest push eugenmayer/unison:2.51.3-4.12.0
docker manifest push eugenmayer/unison:latest
```

I've tested these steps with a [test upload](https://hub.docker.com/repository/docker/hufman/unison/tags), if you'd like to see what it looks like on Docker Hub.

**Comment by EugenMayer** [comment]
@hufman thank you. Do you mind providing a PR to incorporate your findings? This would be great

**Comment by hufman** [comment]
Sure, I could start work on that, I just wasn't sure how active the project's release cadence was! You could run those commands manually to unblock that other ticket for now.

**Comment by hufman** [comment]
Pushed a PR #29 with this approach!
