### ISSUE TITLE
Docker pulls the wrong image for M1 Mac

### ISSUE THREAD

**Issue by yosephsa** [EugenMayer/docker-image-unison#28]
First of all, thank you for your incredible work on docker-sync and the unison repo! I truly cannot say how great that is!

I noticed an issue, when using docker sync on the M1 it is pulling the AMD64 image and not the ARM64. The same happens with I run `docker pull eugenmayer/unison`. 

When starting the image, I get a lot of errors from it being the AMD image on ARM. When starting the container I get this warning

`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

'bash: applet not found'.

When looking at Docker Hub I do not see any images with the OS Archetecture of linux/arm64/v8. I only see linux/arm64. I suspect that is the issue.

For anyone else running into this issue do the following to fix it:
```shell
unisonAmdImage=eugenmayer/unison:$(docker image ls | grep -o '2.*AMD64') ; \
unisonArmImage=eugenmayer/unison:${$(docker image ls | grep -o '2.*AMD64')/AMD/"ARM"} ; \
docker image rm $unisonAmdImage ; \
docker image tag $unisonArmImage $unisonAmdImage
```

**Comment by blackjid** [comment]
You should be able to use the arm tag published on dockerhub https://hub.docker.com/r/eugenmayer/unison/tags for example this is the [2.51.3-4.12.0-ARM64](https://hub.docker.com/layers/unison/eugenmayer/unison/2.51.3-4.12.0-ARM64/images/sha256-b4ec24a0f3c0b361dde06e7c96bef189a51bd578df75a515c741dda2d92bfa35?context=explore)

I'd love to have the image built with multiple architectures using manifests, so you can get the image that is required by you system.

**Comment by yosephsa** [comment]
@blackjid Only issue is that I am not pulling in the image manually, it is being pulled by docker-sync on start of docker-sync. As you can see in the code snippet above I am doing exactly as you suggested. I am pulling the ARM image then retagging it as the AMD image to let docker-sync use the image it expects. 
So as of now this isn't a blocking issue for anyone, just a convenience thing.

**Comment by yosephsa** [comment]
Issue is related to how docker-sync pulls the unison image. It manually specifies the ARM image. Closing issue and opening in docker-sync repo.
