### ISSUE TITLE
Current builds on master are broken

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-image-unison#30]
Currently, we have broken builds on master 

https://app.travis-ci.com/github/EugenMayer/docker-image-unison/builds/254897422

Most probably some patches have changed or something else changed on the static assets we require.

**Comment by yosephsa** [comment]
@EugenMayer I was able to reproduce the error. The UNISON_VERSION being passed into that failing build is 2.51.4_***rc2***.
If you rerun the build with UNISON_VERSION=2.51.4 (or 2.51.5 latest legacy version) it should complete successfully.

**Comment by EugenMayer** [comment]
@yoseph1998 interresting. Now what i ask myself is, what we used _rc2 in the first place. Still, we might just consider going on 2.51.5.

AFAIR one of the issues is, that the versions have to match with the OS version, right. So what ever runs / is installed on MacOS using brew right now, needs to be offered as counterpart as an image. 

With the most recent MacOS / brew, what unison is installed?

**Comment by yosephsa** [comment]
@EugenMayer Not sure why rc2 is being used, quick google tells me rc2 is release candidate 2 which makes this even more peculiar as that's not even the final release (If i understand it correctly).

The most recent version in brew is 2.52.1 https://formulae.brew.sh/formula/unison

Might need to make a PR to update that version inside the Dockerfile constants for consistency's sake.

**Comment by yosephsa** [comment]
@EugenMayer Created a PR to update the constants inside the Dockerfile https://github.com/EugenMayer/docker-image-unison/pull/31

Out of curiosity, where are the version environment variables defined? I don't see them in the repo for the Travis CI environment variables. Are they configured inside Travis CI for this project?

**Comment by EugenMayer** [comment]
Thank you for taking this one on @yoseph1998 !
