### ISSUE TITLE
Error response from daemon: manifest for eugenmayer/unison:latest not found

### ISSUE THREAD

**Issue by JoouulDev** [EugenMayer/docker-image-unison#4]
Hello,
I use this command "docker pull eugenmayer/unison" from https://hub.docker.com/r/eugenmayer/unison/ but i've an error "Error response from daemon: manifest for eugenmayer/unison:latest not found" and I don't found any solution.
Do you have a idea?

**Comment by EugenMayer** [comment]
there is no latest tag

**Comment by michalkleiner** [comment]
@JoouulDev that means you need to specify exact version you want to pull. You can't get `latest`, which is what it's trying to do.
