### ISSUE TITLE
chown: cannot access '/tmp/rundeck': No such file or directory

### ISSUE THREAD

**Issue by JParkinson1991** [EugenMayer/docker-image-unison#7]
Hello,

I think we need to rebuild the 2.51.2.2 image.

```
$ docker run -it eugenmayer/unison:2.51.2.2 /bin/sh
Unable to find image 'eugenmayer/unison:2.51.2.2' locally
2.51.2.2: Pulling from eugenmayer/unison
9a0b0ce99936: Pull complete
7fca71eddb03: Pull complete
30a94eb18637: Pull complete
3abd2af2dfed: Pull complete
58211033cdd6: Pull complete
7648a88ad322: Pull complete
e1673accaf68: Pull complete
d7f68823cc8d: Pull complete
9d06aeeaf7b9: Pull complete
d41509b677ef: Pull complete
Digest: sha256:748750dbd8f7716b1d35bcd0a63d536f8ca05f4aaf8cad3075d1e877618c9630
Status: Downloaded newer image for eugenmayer/unison:2.51.2.2
chown: cannot access '/tmp/rundeck': No such file or directory
```

However, cloning this repository and rebuilding with a new tag seems to be working
```
$ docker build . -t eugenmayer/unison:2.51.2.3
// build output, redacted
$docker run -it eugenmayer/unison:2.51.2.3 /bin/sh                                                                                                                   
/ #
```

My guess is this wasn't apparent post merge yesterday due to me having the one i had built myself available locally.

**Comment by EugenMayer** [comment]
i have rebuild / repushed `eugenmayer/unison:2.51.2.2` sorry for the issue - seems to work now

**Comment by JParkinson1991** [comment]
No need to apologise, thanks for the fix, just tested it's working great!

**Comment by zealouspatcat** [comment]
Hi! I'm having this issue myself
` 
root@vmHostname:/# docker run --name rundeck -p 4440:4440 eugenmayer/rundeck
chown: cannot access '/tmp/rundeck': No such file or directory

`
Is this an error in latest version?
