### ISSUE TITLE
Docker build fails due to binutils version

### ISSUE THREAD

**Issue by twodrops** [EugenMayer/docker-image-unison#8]
The image build failed with the following error:

> ERROR: unsatisfiable constraints:
>   binutils-2.33.1-r0:
>     breaks: world[binutils=2.32-r0]

I could build it only after changing to binutils=2.33.1-r0 (instead of 2.32-r0) in the Dockerfile

**Comment by EugenMayer** [comment]
Thanks, could you provide a PR?

**Comment by twodrops** [comment]
Done
https://github.com/EugenMayer/docker-image-unison/pull/9

**Comment by EugenMayer** [comment]
Thank you! I guess we do not need a new release yet, since it will only fail on rebuild, which is fixed on master now.

Are you fine with that

**Comment by twodrops** [comment]
Sure. That's fine :)
